site_name: Sublime Text Language Server Protocol Documentation
theme: readthedocs
markdown_extensions:
  - admonition

nav:
    - Home: 'index.md'
    - C/C++: 'cplusplus.md'
    - Features: 'features.md'
    - Troubleshooting: 'troubleshooting.md'
